### ISSUE TITLE
crosswalk compatibility

### ISSUE THREAD

**Issue by andrewvmail** [jacquarg/cordova-jsbackgroundservice#3]
just trying to get the plugin working with an app that have crosswalk but having null pointer issue. tried swapping out WebView with XWalkView as the view type but still crashing on createEngine code. just wondering if you guys have any tips or experience working with crosswalk :)

cheers for cool plugin

**Comment by jacquarg** [comment]
Hello, 
Actually, I didn't know Crosswalk before your message : ) .

The difficulty is to make a WebView (a CordovaWebView, or for you a XWalkView) on a headless Service instead of an Activity. 
To make it work, I tried to find a solution to avoid the crash, one after the other ! For an example, in a previous version, I had to create a small and translucent view to make it works.

I can't really give you some real help here, but just a bit of hope ^^ . This plugin is just a big hack, but it works (for now) !
 
Good luck !

**Comment by andrewvmail** [comment]
Thanks for the inspiring message! I think my last hope is i have to use window manager and system wide access. Will post back my findings and result for future people stumbling on this.

Best

**Comment by andrewvmail** [comment]
oops I meant system alert window
